# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 297d41aab0aafbd62574353e98c2e2d2ae38112a5928272bfaa4e3445619da1e3cb3fd97ead1e47745afb15b7595beea85b742021ebcc7c3fe6c2b60945137e9

test:
  secret_key_base: c054111c133de5997e7fa3a3637e2f615a136c9e956bc5246ef7d33bca896fb9ddefc48d3681320a4c8e6395db897168c04e6d51d38b98cd607fb1a54220e6be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
